### ISSUE TITLE
~/.stow-global-ignore doesn't work

### ISSUE THREAD

**Issue by eggbean** [aspiers/stow#89] opened 2021-07-17 15:09 UTC
[This page](https://www.gnu.org/software/stow/manual/stow.html#Types-And-Syntax-Of-Ignore-Lists) mentions that it is possible to make a global `~/.stow-global-ignore`, but it does not seem to work when I make one. I copied this from one of my (working) `.stow-local-ignore` files which I then deleted, but the ignores do not apply:
```
\.git
\.gitignore
.*\.(bak|tmp|notes)
```
The `~/.stow-global-ignore` file is actually a stow symlink itself, but it's the same when making it into an actual file.

I'm using stow (GNU Stow) version 2.3.1.

**Comment by eggbean** [comment] 2022-02-01 00:10
Can anybody else confirm that .stow-global-ignore doesn't work? Does anybody know if it worked in any previous versions? I could consider downgrading to an earlier version if it doesn't have the issues of the current version and if that version doesn't lack any features that I use.

**Comment by gutierri** [comment] 2022-09-19 01:41
I confirm the problem.

The .stow-local-ignore rules override the .stow-global-ignore rules. The ideal would be a mix of the two files.

version: from source ([4ef5eca](https://github.com/aspiers/stow/commit/4ef5eca4a9d107b24e712bb4c2c91f47e7e0fb85))

**Comment by eggbean** [comment] 2022-09-19 04:16
Thanks for confirming this. I use this program heavily, so I'm really looking forward to someone fixing the little bugs present in the current version.

**Comment by gutierri** [comment] 2022-09-27 14:45
I found out where the bug is. I need some time to figure it out. Thinking that the files join the two rules at the end ---- On Mon, 19 Sep 2022 01:17:10 -0300  ***@***.***  wrote ----
Thanks for confirming this. I use this program heavily, so I'm really looking forward to someone fixing the little bugs present in the current version.

**Comment by eggbean** [comment] 2022-09-27 17:30
Me trying to be helpful:

https://metacpan.org/pod/File::Cmp

?

**Comment by gutierri** [comment] 2022-09-28 05:09
The root of the problem is apparently [here](https://github.com/aspiers/stow/blob/master/lib/Stow.pm.in#L1290). It returns the first rule it finds. the ideal would be to end the file checking loop while concatenating what exists.

What prevents this from being quickly fixed by me is time and experience with perl. I'm just a perl hobbyist. And I happen to use stow extensively as well. I hope to fix it soon or maybe some collaborator will help with this too.

https://github.com/aspiers/stow/blob/4ef5eca4a9d107b24e712bb4c2c91f47e7e0fb85/lib/Stow.pm.in#L1273-L1299

**Comment by eggbean** [comment] 2022-09-28 05:46
Ask on StackOverflow?

**Comment by gutierri** [comment] 2022-09-28 22:35
It's not about asking specific questions about perl, but understanding the behavior of the functions used by stow. This code snippet is responsible for validating the rules of the ignore files, but it needs to be understood and understood how the other dependent functions use it and adjusted to include more than 1 value when there is more than 1 file.

**Comment by gutierri** [comment] 2024-04-08 19:14
@aspiers Could you classify this issue as a bug (add label bug)?

**Comment by aspiers** [comment] 2024-04-08 20:00
@gutierri Do you mean this:

> From looking at the verbose log, when there's a .stow-global-ignore, ~/.stow-global-ignore seems to be ignored.

I guess that was a typo and meant to say

> when there's a .stow-local-ignore, ~/.stow-global-ignore seems to be ignored.

That's not a bug - it's working as designed [and documented](https://www.gnu.org/software/stow/manual/html_node/Types-And-Syntax-Of-Ignore-Lists.html), because creating a local ignore file is the currently only way to disable patterns in the global one.

That said, I certainly agree that it would be useful to be able to combine both global and local.  For that ideally we would have something similar to `.gitignore` rules, where you can use `!` to negate a previous rule.  (BTW coincidentally many years ago, [I implemented the `git check-ignore` subcommand](https://stackoverflow.com/questions/12144633/explain-which-gitignore-rule-is-ignoring-my-file/12168102#12168102)!)

**Comment by aspiers** [comment] 2024-04-08 20:02
> Can anybody else confirm that ~/.stow-global-ignore doesn't work?

I can confirm that it definitely does work :stuck_out_tongue_winking_eye:  I've been relying on that for years myself.  But as per my previous comment, it does get overridden by a `.stow-local-ignore`.

**Comment by aspiers** [comment] 2024-04-08 20:03
> When I have `.*\.env` in both files, it still does not get ignored.

This does sound like a bug if true, but if that's reproducible please file a separate issue for it.

**Comment by gutierri** [comment] 2024-04-11 13:08
> @gutierri Do you mean this:
> 
> > From looking at the verbose log, when there's a .stow-global-ignore, ~/.stow-global-ignore seems to be ignored.
> 
> I guess that was a typo and meant to say
> 
> > when there's a .stow-local-ignore, ~/.stow-global-ignore seems to be ignored.
> 
> That's not a bug - it's working as designed [and documented](https://www.gnu.org/software/stow/manual/html_node/Types-And-Syntax-Of-Ignore-Lists.html), because creating a local ignore file is the currently only way to disable patterns in the global one.
> 
> That said, I certainly agree that it would be useful to be able to combine both global and local. For that ideally we would have something similar to `.gitignore` rules, where you can use `!` to negate a previous rule. (BTW coincidentally many years ago, [I implemented the `git check-ignore` subcommand](https://stackoverflow.com/questions/12144633/explain-which-gitignore-rule-is-ignoring-my-file/12168102#12168102)!)

You are right. It was a typing error.


> > When I have `.\*\.env` in both files, it still does not get ignored.
> 
> This does sound like a bug if true, but if that's reproducible please file a separate issue for it.

From this issue(#89), the only thing that needs to be investigated is the `.*\.env`. But I don't know if it makes sense to keep this isue open for that about `.*\.env`. I will analyze this problem in the coming weeks, and come back with some results, if I can reproduce it, I will come back signaling to close this issue and open a new issue about `.*\.env`.

**Comment by aspiers** [comment] 2024-04-12 00:13
Thanks, please do file a new issue if needed.  I don't think it makes sense to keep this one open, because the global ignore definitely does work in general.

**Closed by aspiers** 2024-04-12 00:13 UTC
