### ISSUE TITLE
Precedence warning message appears in 2.4.0

### ISSUE THREAD

**Issue by Thomas-Philippot** [aspiers/stow#115] opened 2024-09-05 07:30 UTC
After a system update stow now display a warning : `Possible precedence issue with control flow operator (exit) at /usr/bin/stow line 839, <DATA> line 23.`

Everything seems to work fine, but the error message is always there.

My system :
- Arch Linux (kernel 6.10.8)
- Stow version 2.4.0

**Comment by aspiers** [comment] 2024-09-05 20:03
This is a duplicate of #113; see https://github.com/aspiers/stow/pull/113#issuecomment-2305940941.

**Closed by aspiers** 2024-09-05 20:03 UTC
