### ISSUE TITLE
cannot stow ".gitignore"

### ISSUE THREAD

**Issue by fenugrec** [aspiers/stow#75] opened 2020-10-30 22:38 UTC
Heh, I just figured it out while writing this (is there a "rubberduck" label ?). So it's not really a bug report anymore, but I'd like to discuss it anyway - feel free to close at any time.

I was trying to stow `~/.gitconfig` and `~/.gitignore` . The first worked, but I just could not make it work with .gitignore !

Turning on -vvvvv revealed the explanation :
```
Using built-in ignore list
    Ignore list regexp for paths:    /(?^:(^|/)(^/README.*|^/LICENSE.*|^/\.stow\-local\-ignore$|^/COPYING)(/|$))/
    Ignore list regexp for segments: /(?^:^(\.hg|CVS|.+,v|\.gitignore|\.svn|#.*#|\.cvsignore|\.#.+|_darcs|.+~|\.git|RCS)$)/
```
I understand the reason for ignoring those in the root of the "stow directory", but I'm not sure when they would be a problem coming from within a package ?
Unless those regexp are mainly so that --adopt doesn't pick up all that trash ?

I know how to work around this ; just add --dotfiles in .stowrc , and rename files to `dot-gitconfig` and `dot-gitignore`, so as I said this isn't really an issue.

**Comment by aspiers** [comment] 2021-04-04 23:42
The point is that typically when stowing from a package which is a git repo, the .gitignore at the top of that repo is intended only for use within the git repo, and should not be stowed into `~` or `/usr/local` or wherever the stow target directory is.  The only exception is when you want to use Stow to manage `~/.gitignore` (say) as a symlink pointing to a file version-controlled with git.  In that case, you can set up a `.stow-local-ignore` just for that git repo which overrides Stow's default ignore list and allows the `.gitignore` to be stowed.  In fact I do exactly that myself: https://github.com/aspiers/git-config/blob/master/.stow-local-ignore

Hope that makes sense, and sorry for the slow reply!  Closing for now, but happy to reopen if anything is unclear.

**Closed by aspiers** 2021-04-04 23:42 UTC
Labels: question

**Comment by fenugrec** [comment] 2021-04-05 00:09
>  and sorry for the slow reply! 
Haha no worries I've seen worse.

Thanks for the alternate solution, I wasn't aware of .stow-local-ignore.
I still think it's an interesting edge case / typical scenario; next time someone asks it may need to be added to the FAQ !

**Comment by aspiers** [comment] 2021-04-05 14:43
[**@fenugrec**](https://github.com/fenugrec) commented on [April 5, 2021 1:09 AM](https://github.com/aspiers/stow/issues/75#issuecomment-813121091 "2021-04-05T00:09:23Z - Replied by Github Reply Comments"):
> >  and sorry for the slow reply! 
> 
> Haha no worries I've seen / done worse.

:laughing:  Thanks for your patience!

> Thanks for the alternate solution, I wasn't aware of .stow-local-ignore.
> I still think it's an interesting edge case / typical scenario; next time someone asks it may need to be added to the FAQ !

Yep, fair point.  We don't actually have a FAQ yet, but there is [a section on Ignore Lists in the manual](https://www.gnu.org/software/stow/manual/html_node/Ignore-Lists.html).  If you have any ideas for how to improve that, I'd be happy to hear them!

**Comment by anotherglitchinthematrix** [comment] 2021-07-14 09:07
As an addition to the topic, if you're stowing the hyerarchy like in the example below it will be enough to put an empty `.stow-local-ignore` file in to the directory.

```
.dotfiles
├── .gitignore
├── .stow
├── README.md
├── git
.   ├── .gitconfig
.   ├── .gitignore
.   └── .stow-local-ignore
```

**Comment by saltsucker** [comment] 2022-05-14 06:02
Hmm.. I must not be as savvy as OP, but can't seem to understand the issue. I wonder if I am doing something wrong?

I put my `.gitconfig` and `.gitignore` in `~/.dotfiles/git` which is vc'd using a normal git repo that makes `~/` as my work-tree (have an alias, similar to the "bare" concept, just not a bare repo basically). This seems to work fine. I think because I set my work-tree to $HOME. So it pulls the gitignore from home. Not my dotfiles. Does that make sense?

**Comment by afrid18** [comment] 2022-08-21 18:15
I don't have .gitignore file in the .stow-global-ignore and yet I am unable to stow it.

Here is my verbose output:
```
  dotfiles/git/.stow-local-ignore didn't exist
  /Users/imamkhaja/.stow-global-ignore didn't exist
  Using built-in ignore list
    Ignore list regexp for paths:    /(?^:(^|/)(^/\.stow\-local\-ignore$|^/COPYING|^/LICENSE.*|^/README.*)(/|$))/
    Ignore list regexp for segments: /(?^:^(\.git|.+~|_darcs|.+,v|RCS|\.gitignore|#.*#|CVS|\.cvsignore|\.svn|\.#.+|\.hg)$)/
  Ignoring path segment .gitignore
```

It seems that segments ignore list is the reason, that .gitignore isn't stowing, if I am not worng.

<img width="787" alt="Screenshot 2022-08-21 at 11 34 43 PM" src="https://user-images.githubusercontent.com/59523682/185804755-9ec306e2-4a57-4872-b5fc-f5699bc4d25f.png">

**Comment by fenugrec** [comment] 2022-12-22 14:31
quoting the first post :

> just add --dotfiles in .stowrc , and rename files to dot-gitconfig and dot-gitignore, so as I said this isn't really an issue.

that's how I solved it

**Comment by FWDekker** [comment] 2023-09-14 14:24
@afrid18 @nineboxes Just create an empty `.stow-local-ignore` in `~/.dotfiles/git`. The point is not to override your global ignore file, but to override Stow's internal default ignore file.

**Comment by 1player** [comment] 2024-09-08 08:55
This is still an issue with the --dotfiles option. I understand the rationale of ignoring `.gitignore`, but `dot-gitignore` is also skipped which is a bug.

**Comment by aspiers** [comment] 2024-09-08 10:01
@1player Did you try [this](https://github.com/aspiers/stow/issues/75#issuecomment-1719558252)?

**Comment by 1player** [comment] 2024-09-08 11:06
I did and fixes it, but it seems to me stow should rightly ignore .gitignore by default, but not dot-gitignore. 

In other words, checking if a file should be skipped should happen _before_ replacing the dot- string in the filename with a literal dot, which how I expected it to behave.

**Comment by aspiers** [comment] 2024-09-08 11:19
I think you are right, because something called `dot-gitignore` is obviously named that way because it was intended to be stowed.  Please could you file a separate issue for that?  I have checked the code and it looks like it's probably easy to fix.

**Comment by aspiers** [comment] 2024-09-08 12:11
Fix submitted as #116, please can you test?

**Comment by rrevi** [comment] 2026-05-01 08:27
> This is still an issue with the --dotfiles option. I understand the rationale of ignoring `.gitignore`, but `dot-gitignore` is also skipped which is a bug.

Having this same issue right now with stow version 2.4.1 (on macOS; not an issue in my Linux env) when I run `stow --dotfiles git`

@aspiers , yes I tried [that](https://github.com/aspiers/stow/issues/75#issuecomment-1719558252).

```
$ tree -a -I '.git'
.
├── .gitignore
├── .gitmessage
├── .ruby-lsp
│   ├── .gitignore
│   ├── Gemfile
│   ├── Gemfile.lock
│   └── last_updated
├── LICENSE.md
├── README.md
├── Terminal
│   └── rrevi.terminal
├── VSCodium
│   └── rrevi.code-profile
├── bin
│   ├── replace
│   └── tat
├── config
│   ├── .agignore
│   ├── .aliases
│   ├── .gemrc
│   ├── .hushlogin
│   ├── .nanorc
│   ├── .pryrc
│   ├── .psqlrc
│   └── .rspec
├── fish
│   └── .config
│       └── fish
│           └── config.fish
├── git
│   ├── .gitconfig
│   ├── .stow-local-ignore
│   └── dot-gitignore
├── homebrew
│   └── Brewfile
├── iterm2
│   ├── SolarizedDark.itermcolors
│   ├── SolarizedLight.itermcolors
│   ├── rrevi-fish.json
│   └── rrevi-zsh.json
├── scripts
│   └── macOS.sh
├── setup.sh
└── zsh
    ├── .zlogin
    ├── .zlogout
    ├── .zprofile
    ├── .zshenv
    └── .zshrc
```

Maybe this is macOS specific?

**Comment by rrevi** [comment] 2026-05-01 12:38
> > This is still an issue with the --dotfiles option. I understand the rationale of ignoring `.gitignore`, but `dot-gitignore` is also skipped which is a bug.
> 
> Having this same issue right now with stow version 2.4.1 (on macOS; not an issue in my Linux env) when I run `stow --dotfiles git`
> 
> [@aspiers](https://github.com/aspiers) , yes I tried [that](https://github.com/aspiers/stow/issues/75#issuecomment-1719558252).
> 
> ```
> $ tree -a -I '.git'
> .
> ├── .gitignore
> ├── .gitmessage
> ├── .ruby-lsp
> │   ├── .gitignore
> │   ├── Gemfile
> │   ├── Gemfile.lock
> │   └── last_updated
> ├── LICENSE.md
> ├── README.md
> ├── Terminal
> │   └── rrevi.terminal
> ├── VSCodium
> │   └── rrevi.code-profile
> ├── bin
> │   ├── replace
> │   └── tat
> ├── config
> │   ├── .agignore
> │   ├── .aliases
> │   ├── .gemrc
> │   ├── .hushlogin
> │   ├── .nanorc
> │   ├── .pryrc
> │   ├── .psqlrc
> │   └── .rspec
> ├── fish
> │   └── .config
> │       └── fish
> │           └── config.fish
> ├── git
> │   ├── .gitconfig
> │   ├── .stow-local-ignore
> │   └── dot-gitignore
> ├── homebrew
> │   └── Brewfile
> ├── iterm2
> │   ├── SolarizedDark.itermcolors
> │   ├── SolarizedLight.itermcolors
> │   ├── rrevi-fish.json
> │   └── rrevi-zsh.json
> ├── scripts
> │   └── macOS.sh
> ├── setup.sh
> └── zsh
>     ├── .zlogin
>     ├── .zlogout
>     ├── .zprofile
>     ├── .zshenv
>     └── .zshrc
> ```
> 
> Maybe this is macOS specific?

apparently I needed to use the target option `-t` on macOS (which I don't use on Linux and it works there without it)
